### ISSUE TITLE
How did you get Hash function?

### ISSUE THREAD

**Issue by SethKitchen** [tylerkahn/connect4-qlearning#1]
Interested how you knew what hash function to use for StateAction.

**Comment by tylerkahn** [comment]
It basically just maps each slot in the grid to a 0 or 1 depending on who placed the disc in that slot and then puts that bitwise into a 64 bit integer (i.e. 00010111) – it assumes size_t is 64 bits.

There's probably a much more efficient way to do this but I just needed something plausible. I could have just returned 1 but then the hash collisions would have made the lookups into the hash table O(n) instead of O(1) which is what I wanted.

I did this back in college just to explore Q-learning. Thanks for the question!

**Comment by SethKitchen** [comment]
Wait so 6x7 = 42 slots. Are the other 22 bits just 0s?

This is a great project - I ported it to C# and it is a little faster :P

**Comment by tylerkahn** [comment]
Yup the other 22 bits are 0.

That's awesome. Let me know when you upload it and I'll take a look.

**Comment by tylerkahn** [comment]
Actually the result appends to the end 4 bits which represent the action taken. So it's 18 zeros + 1s and 0s for each slot + 4 bits for the action taken. The action is which column the disc was placed in.

**Comment by SethKitchen** [comment]
https://github.com/SethKitchen/QLearningConnect4CSPort is the uploaded cs version. thanks for the help!
